import type { ContentRepository } from './schema'

const capabilities = {
  it: [
    { id: 'embedded-systems', category: 'embedded', label: 'Sistemi embedded' },
    { id: 'architecture-governance', category: 'architecture', label: 'Architettura e governance' },
    { id: 'spring-backend', category: 'backend', label: 'Backend Spring Boot' },
    { id: 'domain-modeling', category: 'architecture', label: 'Domain modeling' },
    { id: 'python-automation', category: 'backend', label: 'Automazione Python' },
    { id: 'deterministic-pipelines', category: 'architecture', label: 'Pipeline deterministiche' },
    { id: 'laravel-api', category: 'backend', label: 'API Laravel' },
    { id: 'containerized-delivery', category: 'delivery', label: 'Delivery containerizzata' },
  ],
  en: [
    { id: 'embedded-systems', category: 'embedded', label: 'Embedded systems' },
    { id: 'architecture-governance', category: 'architecture', label: 'Architecture and governance' },
    { id: 'spring-backend', category: 'backend', label: 'Spring Boot backend' },
    { id: 'domain-modeling', category: 'architecture', label: 'Domain modelling' },
    { id: 'python-automation', category: 'backend', label: 'Python automation' },
    { id: 'deterministic-pipelines', category: 'architecture', label: 'Deterministic pipelines' },
    { id: 'laravel-api', category: 'backend', label: 'Laravel API' },
    { id: 'containerized-delivery', category: 'delivery', label: 'Containerised delivery' },
  ],
} as const

export const rawContentRepository: ContentRepository = {
  projects: [
    {
      id: 'homeedge-ai-platform',
      status: 'active',
      capabilityIds: ['embedded-systems', 'architecture-governance'],
      evidence: [
        {
          id: 'homeedge-repository',
          type: 'repository',
          label: 'HomeEdge AI Platform repository',
          url: 'https://github.com/pianic2/homeedge-ai-platform',
          description: 'Versioned firmware, product boundaries, governance documents and technical decisions.',
        },
      ],
      links: [
        { kind: 'repository', url: 'https://github.com/pianic2/homeedge-ai-platform', label: 'GitHub' },
      ],
      assetIds: [],
      featured: true,
      order: 0,
    },
    {
      id: 'restaurant-kitchef-brain',
      status: 'completed',
      capabilityIds: ['spring-backend', 'domain-modeling'],
      evidence: [
        {
          id: 'kitchef-repository',
          type: 'repository',
          label: 'Restaurant Kitchef Brain repository',
          url: 'https://github.com/pianic2/its-java-restaurant-kitchef-brain',
          description: 'Spring Boot source, database migrations, API documentation and automated tests.',
        },
      ],
      links: [
        { kind: 'repository', url: 'https://github.com/pianic2/its-java-restaurant-kitchef-brain', label: 'GitHub' },
      ],
      assetIds: [],
      featured: true,
      order: 1,
    },
    {
      id: 'ai-social-agent',
      status: 'maintained',
      capabilityIds: ['python-automation', 'deterministic-pipelines'],
      evidence: [
        {
          id: 'ai-social-repository',
          type: 'repository',
          label: 'AI Social Agent repository',
          url: 'https://github.com/pianic2/ai-social',
          description: 'Implemented runtime and layered architecture with documented transitional areas.',
        },
      ],
      links: [{ kind: 'repository', url: 'https://github.com/pianic2/ai-social', label: 'GitHub' }],
      assetIds: [],
      featured: false,
      order: 2,
    },
    {
      id: 'its-libreria-api',
      status: 'completed',
      capabilityIds: ['laravel-api', 'containerized-delivery'],
      evidence: [
        {
          id: 'libreria-repository',
          type: 'repository',
          label: 'ITS Libreria API repository',
          url: 'https://github.com/pianic2/its-php-libreria',
          description: 'Laravel REST API documentation, Docker bootstrap, authentication and test guidance.',
        },
      ],
      links: [
        { kind: 'repository', url: 'https://github.com/pianic2/its-php-libreria', label: 'GitHub' },
      ],
      assetIds: [],
      featured: false,
      order: 3,
    },
  ],
  assets: [],
  locales: {
    it: {
      locale: 'it',
      identity: { name: 'Niccolò Piazzi', descriptor: 'Full-stack developer e progettista di sistemi' },
      navigation: [
        { page: 'home', label: 'Home' },
        { page: 'projects', label: 'Progetti' },
        { page: 'skills', label: 'Competenze' },
        { page: 'method', label: 'Metodo' },
        { page: 'profile', label: 'Profilo' },
        { page: 'contact', label: 'Contatti' },
      ],
      common: {
        projectLabel: 'Progetto',
        repositoryLabel: 'Repository',
        evidenceLabel: 'Evidenze',
        unknownProjectTitle: 'Progetto non trovato',
        unknownProjectDescription: 'Lo slug richiesto non corrisponde a un progetto pubblicato.',
        placeholderDescription: 'Il contenuto della pagina sarà composto usando il content layer validato.',
      },
      capabilities: [...capabilities.it],
      projects: [
        {
          projectId: 'homeedge-ai-platform',
          slug: 'homeedge-ai-platform',
          title: 'HomeEdge AI Platform',
          eyebrow: 'Edge e smart home',
          summary: 'Piattaforma smart home edge-first costruita attorno a un nodo MVP ESP32-C3 e a confini architetturali espliciti.',
          problem: 'Progettare una piattaforma smart home verificabile senza presentare come già implementati servizi backend, mobile o AI ancora in evoluzione.',
          approach: 'Separazione tra firmware MVP, architettura target, decisioni, rischi e governance con GitHub come sorgente della verità tecnica.',
          outcome: 'Repository Sprint 0 con firmware e confini MVP documentati; i servizi backend, mobile e AI restano dichiarati come direzione non ancora validata.',
          role: 'Project owner e sviluppatore.',
          claim: { status: 'demonstrated', evidenceIds: ['homeedge-repository'] },
          metadata: { title: 'HomeEdge AI Platform', description: 'Progetto edge-first per smart home con ESP32-C3, firmware e governance tecnica.' },
        },
        {
          projectId: 'restaurant-kitchef-brain',
          slug: 'restaurant-kitchef-brain',
          title: 'Restaurant Kitchef Brain',
          eyebrow: 'Java e domain modeling',
          summary: 'Backend Spring Boot per modellare ordini, postazioni di cucina, workflow operativi e metriche di servizio.',
          problem: 'Rappresentare il lavoro di cucina con transizioni valide, storico temporale e protezione dagli aggiornamenti concorrenti.',
          approach: 'Dominio ricco con state machine delle righe ordine, persistenza PostgreSQL, migration Flyway, optimistic locking e API REST.',
          outcome: 'API documentate per tavoli, ordini, kitchen board e metriche, con test automatici eseguibili tramite Maven.',
          role: 'Sviluppatore backend e modellatore del dominio.',
          claim: { status: 'demonstrated', evidenceIds: ['kitchef-repository'] },
          metadata: { title: 'Restaurant Kitchef Brain', description: 'Backend Spring Boot con state machine, kitchen board e metriche operative.' },
        },
        {
          projectId: 'ai-social-agent',
          slug: 'ai-social-agent',
          title: 'AI Social Agent',
          eyebrow: 'Automazione e pipeline',
          summary: 'Sistema Python per orchestrare una pipeline deterministica di contenuti e conservare artefatti e stato operativo in modo ispezionabile.',
          problem: 'Automatizzare un flusso di produzione mantenendo comportamento deterministico, ripartenza controllata e confini chiari tra dominio e infrastruttura.',
          approach: 'Architettura a livelli, artefatti filesystem-first, persistenza SQLite ed esplicite state machine per i cicli operativi.',
          outcome: 'Runtime e moduli principali implementati, con alcune aree legacy e documentazione ancora in consolidamento dichiarate nel repository.',
          role: 'Progettista e sviluppatore del sistema.',
          claim: { status: 'demonstrated', evidenceIds: ['ai-social-repository'] },
          metadata: { title: 'AI Social Agent', description: 'Pipeline Python deterministica con artefatti filesystem-first e stato persistente.' },
        },
        {
          projectId: 'its-libreria-api',
          slug: 'its-libreria-api',
          title: 'ITS Libreria API',
          eyebrow: 'PHP e Laravel',
          summary: 'API REST Laravel per gestire libri, autori, categorie, autenticazione token e contenuti testuali associati.',
          problem: 'Realizzare un backend didattico completo, riproducibile e orientato alle API con relazioni, validazione e operazioni protette.',
          approach: 'Laravel, Sanctum, MySQL e Docker Compose con bootstrap automatico, Form Request e test applicativi.',
          outcome: 'API documentata e containerizzata con endpoint pubblici di lettura, scritture autenticate e download dei file associati ai libri.',
          role: 'Sviluppatore backend.',
          claim: { status: 'demonstrated', evidenceIds: ['libreria-repository'] },
          metadata: { title: 'ITS Libreria API', description: 'REST API Laravel containerizzata con Sanctum, MySQL e validazione.' },
        },
      ],
    },
    en: {
      locale: 'en',
      identity: { name: 'Niccolò Piazzi', descriptor: 'Full-stack developer and systems designer' },
      navigation: [
        { page: 'home', label: 'Home' },
        { page: 'projects', label: 'Projects' },
        { page: 'skills', label: 'Skills' },
        { page: 'method', label: 'Method' },
        { page: 'profile', label: 'Profile' },
        { page: 'contact', label: 'Contact' },
      ],
      common: {
        projectLabel: 'Project',
        repositoryLabel: 'Repository',
        evidenceLabel: 'Evidence',
        unknownProjectTitle: 'Project not found',
        unknownProjectDescription: 'The requested slug does not match a published project.',
        placeholderDescription: 'This page will be composed from the validated content layer.',
      },
      capabilities: [...capabilities.en],
      projects: [
        {
          projectId: 'homeedge-ai-platform',
          slug: 'homeedge-ai-platform',
          title: 'HomeEdge AI Platform',
          eyebrow: 'Edge and smart home',
          summary: 'An edge-first smart home platform built around an ESP32-C3 MVP node and explicit architectural boundaries.',
          problem: 'Design a reviewable smart home platform without presenting evolving backend, mobile or AI services as already implemented.',
          approach: 'Separate MVP firmware, target architecture, decisions, risks and governance, with GitHub as the technical source of truth.',
          outcome: 'A Sprint 0 repository with documented firmware and MVP boundaries; backend, mobile and AI services remain explicitly unvalidated directions.',
          role: 'Project owner and developer.',
          claim: { status: 'demonstrated', evidenceIds: ['homeedge-repository'] },
          metadata: { title: 'HomeEdge AI Platform', description: 'Edge-first smart home project with ESP32-C3 firmware and technical governance.' },
        },
        {
          projectId: 'restaurant-kitchef-brain',
          slug: 'restaurant-kitchef-brain',
          title: 'Restaurant Kitchef Brain',
          eyebrow: 'Java and domain modelling',
          summary: 'A Spring Boot backend modelling orders, kitchen stations, operational workflows and service metrics.',
          problem: 'Represent kitchen work through valid transitions, temporal history and protection against concurrent updates.',
          approach: 'A rich domain model with an order-line state machine, PostgreSQL persistence, Flyway migrations, optimistic locking and REST APIs.',
          outcome: 'Documented APIs for tables, orders, the kitchen board and metrics, with automated tests executable through Maven.',
          role: 'Backend developer and domain modeller.',
          claim: { status: 'demonstrated', evidenceIds: ['kitchef-repository'] },
          metadata: { title: 'Restaurant Kitchef Brain', description: 'Spring Boot backend with a state machine, kitchen board and operational metrics.' },
        },
        {
          projectId: 'ai-social-agent',
          slug: 'ai-social-agent',
          title: 'AI Social Agent',
          eyebrow: 'Automation and pipelines',
          summary: 'A Python system orchestrating a deterministic content pipeline while keeping artifacts and operational state inspectable.',
          problem: 'Automate a production workflow while preserving deterministic behaviour, controlled restarts and clear domain-to-infrastructure boundaries.',
          approach: 'Layered architecture, filesystem-first artifacts, SQLite persistence and explicit state machines for operational lifecycles.',
          outcome: 'The runtime and principal modules are implemented, while declared legacy areas and documentation consolidation remain visible in the repository.',
          role: 'System designer and developer.',
          claim: { status: 'demonstrated', evidenceIds: ['ai-social-repository'] },
          metadata: { title: 'AI Social Agent', description: 'Deterministic Python pipeline with filesystem-first artifacts and persistent state.' },
        },
        {
          projectId: 'its-libreria-api',
          slug: 'its-libreria-api',
          title: 'ITS Libreria API',
          eyebrow: 'PHP and Laravel',
          summary: 'A Laravel REST API managing books, authors, categories, token authentication and associated text content.',
          problem: 'Build a complete, reproducible API-first educational backend with relationships, validation and protected operations.',
          approach: 'Laravel, Sanctum, MySQL and Docker Compose with automatic bootstrap, Form Requests and application tests.',
          outcome: 'A documented and containerised API with public reads, authenticated writes and downloads for book text files.',
          role: 'Backend developer.',
          claim: { status: 'demonstrated', evidenceIds: ['libreria-repository'] },
          metadata: { title: 'ITS Libreria API', description: 'Containerised Laravel REST API with Sanctum, MySQL and validation.' },
        },
      ],
    },
  },
}
